
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ dev ]
   

  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'ap-south-1'
    - name: Upload files to S3 with AWS CLI
      run:  
       aws cloudformation package --template-file main_template.yaml --s3-bucket buck5tr --output-template-file main_template.yaml
 
    - name: Deploy CloudFormation Stack
      run:
       aws cloudformation deploy --template-file main_template.yaml --stack-name RootStack --capabilities CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND
#      uses: aws-actions/aws-cloudformation-github-deploy@v1.0.3
#      with:
#        name: RootStack
#        template: main_template.yaml
#        iam-capabilities: CAPABILITY_IAM
        


